# PIPELINE DEFINITION
# Name: ml-pipeline
components:
  comp-age-model-training-component:
    executorLabel: exec-age-model-training-component
  comp-data-preprocessing-component:
    executorLabel: exec-data-preprocessing-component
  comp-tensorizing-component:
    executorLabel: exec-tensorizing-component
deploymentSpec:
  executors:
    exec-age-model-training-component:
      container:
        image: abzp/ac215-age-model-training:abpujare
    exec-data-preprocessing-component:
      container:
        image: nevilgeorge/eng-ai-preprocessing
    exec-tensorizing-component:
      container:
        image: abzp/eng-ai-tensorizing:abpujare
pipelineInfo:
  name: ml-pipeline
root:
  dag:
    tasks:
      age-model-training-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-age-model-training-component
        dependentTasks:
        - tensorizing-component
        taskInfo:
          name: Model Training
      data-preprocessing-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-preprocessing-component
        taskInfo:
          name: Data Preprocessing
      tensorizing-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-tensorizing-component
        dependentTasks:
        - data-preprocessing-component
        taskInfo:
          name: Tensorizing
schemaVersion: 2.1.0
sdkVersion: kfp-2.3.0
